name: dayline_app
description: A local-first life record app skeleton.
publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: ^3.9.0
  flutter: '>=3.35.0'

dependencies:
  flutter:
    sdk: flutter
  archive: ^4.0.9
  crypto: ^3.0.7
  flutter_riverpod: ^3.3.1
  go_router: ^17.2.2
  path: ^1.9.1
  path_provider: ^2.1.5
  record: ^6.2.0
  sherpa_onnx: ^1.13.1
  sqflite: ^2.4.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  sqflite_common_ffi: ^2.3.6

flutter:
  uses-material-design: true
  assets:
    - assets/stt/
